name: FTP deploy on push

on:
  push:
    branches:
      - dev

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Sync files via lftp
        run: |
          sudo apt-get install -y lftp
          lftp -u ${{ secrets.FTP_USER }},${{ secrets.FTP_PASSWORD }} ${{ secrets.REMOTE_HOST }} -e "
            set ftp:passive-mode yes;
            set net:timeout 30;
            set net:max-retries 3;
            mirror --reverse --delete --verbose ./ ${{ secrets.FTP_PATH }};
            quit"
